require "rake"
require_relative "../../Rakefile_common.rb"

task :default => [:install_osx]

desc "download {fmt} lib"
task :download do
  cmd = "git clone --depth=1 https://github.com/fmtlib/fmt.git"
  system( cmd );
end

CMAKEDEFINES = '-DCMAKE_CXX_STANDARD:VAR="11" -DFMT_DOC:VAR=NO  -DFMT_TEST:VAR=NO -DFMT_FUZZ:VAR=NO --loglevel=WARNING '

desc "build {fmt} lib for osx"
task :build_osx => [:download] do
  FileUtils.cd      'fmt'
  FileUtils.rm_rf   'build'
  FileUtils.mkdir_p 'build'
  FileUtils.cd      'build'
  if COMPILE_DEBUG then
    sh 'cmake -DCMAKE_BUILD_TYPE:VAR=Debug -DCMAKE_INSTALL_PREFIX:PATH=../lib ' + CMAKEDEFINES + '..'
    sh 'cmake --build . --clean-first --config Debug --target install '+PARALLEL+QUIET
    FileUtils.mv '../lib/lib/libfmt.a', "../lib/lib/libfmt_osx_static_debug.a"
  end
  sh 'cmake -DCMAKE_BUILD_TYPE:VAR=Release -DCMAKE_INSTALL_PREFIX:PATH=../lib ' + CMAKEDEFINES + '..'
  sh 'cmake --build . --clean-first --config Release --target install '+PARALLEL+QUIET
  FileUtils.mv '../lib/lib/libfmt.a', "../lib/lib/libfmt_osx_static.a"
  FileUtils.cd '../..'
  Rake::Task[:install_common].invoke()
end

desc "build {fmt} lib for linux"
task :build_linux => [:download] do
  FileUtils.cd      'fmt'
  FileUtils.rm_rf   'build'
  FileUtils.mkdir_p 'build'
  FileUtils.cd      'build'
  if COMPILE_DEBUG then
    sh 'cmake -DCMAKE_BUILD_TYPE:VAR=Debug -DCMAKE_INSTALL_PREFIX:PATH=../lib ' + CMAKEDEFINES + '..'
    sh 'cmake --build . --clean-first --config Debug --target install '+PARALLEL+QUIET
    FileUtils.mv '../lib/lib/libfmt.a', "../lib/lib/libfmt_linux_static_debug.a"
  end
  sh 'cmake -DCMAKE_BUILD_TYPE:VAR=Release -DCMAKE_INSTALL_PREFIX:PATH=../lib ' + CMAKEDEFINES + '..'
  sh 'cmake --build . --clean-first --config Release --target install '+PARALLEL+QUIET
  FileUtils.mv '../lib/lib/libfmt.a', "../lib/lib/libfmt_linux_static.a"
  FileUtils.cd '../..'
  Rake::Task[:install_common].invoke()
end

desc "build {fmt} lib for windows"
task :build_win, [:year, :bits] => [:download] do |t, args|
  args.with_defaults(:year => "2017", :bits => "x64" )

  FileUtils.cd      'fmt'
  FileUtils.rm_rf   'build'
  FileUtils.mkdir_p 'build'
  FileUtils.cd      'build'
  if COMPILE_DEBUG then
    sh 'cmake -DCMAKE_BUILD_TYPE:VAR=Debug -DCMAKE_INSTALL_PREFIX:PATH=../lib ' + CMAKEDEFINES + '..'
    sh 'cmake --build . --clean-first --config Debug --target install '+PARALLEL+QUIET
    FileUtils.mv './Debug/fmt.lib', "../lib/lib/fmt_win_#{args.bits}_static_debug.lib"
  end
  sh 'cmake -DCMAKE_BUILD_TYPE:VAR=Release -DCMAKE_INSTALL_PREFIX:PATH=../lib ' + CMAKEDEFINES + '..'
  sh 'cmake --build . --clean-first --config Release --target install '+PARALLEL+QUIET
  FileUtils.mv './Release/fmt.lib', "../lib/lib/fmt_win_#{args.bits}_static.lib"
  FileUtils.cd '../..'
  Rake::Task[:install_common].invoke()
end


task :install_common do |t, args|
  prefix = "../../lib3rd"
  puts "{fmt} copy files to #{prefix}"
  FileUtils.mkdir_p "#{prefix}/include/fmt"
  FileUtils.mkdir_p "#{prefix}/lib"
  Dir['fmt/lib/include/fmt/*'].each do |f|
    if File.file?(f) then
      puts "Copy header #{File.basename(f)}".green
      FileUtils.cp f, prefix+'/include/fmt/'+File.basename(f)
    end
  end
  Dir['fmt/lib/lib/*'].each do |f|
    if File.file?(f) then
      puts "Copy static lib #{File.basename(f)}".green
      FileUtils.cp f, prefix+'/lib/'+File.basename(f)
    end
  end
  FileUtils.cp 'fmt/LICENSE.rst', '../../license/fmt_license.txt'
end

desc "install locally {fmt} lib for linux"
task :install_linux => [:build_linux] do
end

desc "install locally {fmt} lib for osx"
task :install_osx => [:build_osx] do
end

desc "install locally {fmt} lib for windows"
task :install_win, [:year, :bits] do |t, args|
  args.with_defaults(:year => "2017", :bits => "x64" )
  Rake::Task[:build_win].invoke(args.year, args.bits)
end

desc "clean {fmt} for linux"
task :clean_linux do
  FileUtils.rm_rf "lib"
  FileUtils.rm_rf "fmt"
end

desc "clean {fmt} for osx"
task :clean_osx do
  FileUtils.rm_rf "lib"
  FileUtils.rm_rf "fmt"
end

desc "clean {fmt} for windows"
task :clean_win do
  FileUtils.rm_rf "lib"
  FileUtils.rm_rf "fmt"
end
