require "rake"
require "../../cmake_utils/Rakefile_common.rb"

desc "install locally OpenBlas for Linux (do nothing)"
task :install_linux do
end

desc "install locally OpenBlas for OSX (do nothing)"
task :install_osx do
end

desc "install locally OpenBlas for MINGW (do nothing)"
task :install_mingw do
end

desc "install locally OpenBlas for Windows"
task :install_win do
  # check architecture
  case `where cl.exe`.chop
  when /x64\\cl\.exe/
    VS_ARCH = 'x64'
  when /amd64\\cl\.exe/
    VS_ARCH = 'x64'
  when /bin\\cl\.exe/
    VS_ARCH = 'x86'
  else
    raise RuntimeError, "Cannot determine architecture for Visual Studio".red
  end

  FileUtils.mkdir_p "../../lib3rd/lib"
  FileUtils.mkdir_p "../../lib3rd/dll"
  FileUtils.mkdir_p "../../lib3rd/bin/"+VS_ARCH
  FileUtils.mkdir_p "../../src/openblas/"+VS_ARCH+"/"
  Dir[VS_ARCH+'/dll/*'].each{ |f| FileUtils.cp(f,'../../lib3rd/dll/'+File.basename(f)) }
  Dir[VS_ARCH+'/lib/*'].each{ |f| FileUtils.cp(f,'../../lib3rd/lib/'+File.basename(f)) }
  Dir[VS_ARCH+'/bin/*.dll'].each do |f|
    FileUtils.cp(f,'../../lib3rd/bin/'+VS_ARCH+'/'+File.basename(f))
  end
  Dir[VS_ARCH+'/include/*.h'].each do |f|
    FileUtils.cp(f,'../../src/openblas/'+VS_ARCH+'/'+File.basename(f))
  end
end

desc "clean Openblas for LINUX"
task :clean_linux do
end

desc "clean Openblas for OSX"
task :clean_osx do
end

desc "clean Openblas for WINDOWS"
task :clean_win do
end

desc "clean Openblas for MINGW"
task :clean_mingw do
end
