require_relative "../../cmake_utils/Rakefile_common.rb"

task :default => :install_osx do end

VER='5.3.0'
FILENAME="superlu-#{VER}.tar.gz"

desc "download superlu-#{VER}.tar.gz lib"
task :download do
  if File.exists?(FILENAME) then
    url_download( "https://github.com/xiaoyeli/superlu/archive/refs/tags/v#{VER}.tar.gz", FILENAME )
  end
end

if COMPILE_DEBUG then
  endname = "_static_debug"
else
  endname = "_static"
end

def ChangeOnFile( file, text_to_replace, text_to_put_in_place )
  text= File.read file
  File.open(file, 'w+'){|f| f << text.gsub(text_to_replace, text_to_put_in_place)}
end

def extract_and_prepare()
  extract_tgz(FILENAME)
  FileUtils.rm_rf 'superlu'
  FileUtils.mv    'superlu-'+VER, 'superlu'

  ChangeOnFile("./superlu/SRC/creadrb.c","#ifdef DEBUG","#ifdef DISABLED_DEBUG")
  ChangeOnFile("./superlu/SRC/creadhb.c","#ifdef DEBUG","#ifdef DISABLED_DEBUG")
  ChangeOnFile("./superlu/SRC/zreadrb.c","#ifdef DEBUG","#ifdef DISABLED_DEBUG")
  ChangeOnFile("./superlu/SRC/zreadhb.c","#ifdef DEBUG","#ifdef DISABLED_DEBUG")

  FileUtils.rm_rf 'build'
  FileUtils.mkdir 'build'
end

def extract_and_prepare_and_compile( os )
  extract_and_prepare()
  FileUtils.cd 'build'
  if COMPILE_DEBUG then
    sh 'cmake -G Ninja -DCMAKE_BUILD_TYPE:VAR=Debug -DCMAKE_INSTALL_PREFIX:PATH=../lib --loglevel=STATUS ..'
    sh 'cmake --build . --clean-first --config Debug --target install '+PARALLEL
    FileUtils.mv '../lib/lib/libsuperlu.a', "../lib/lib/libsuperlu_#{os}_static_debug.a"
  else
    sh 'cmake -G Ninja -DCMAKE_BUILD_TYPE:VAR=Release -DCMAKE_INSTALL_PREFIX:PATH=../lib --loglevel=STATUS ..'
    sh 'cmake --build . --clean-first --config Release --target install '+PARALLEL
    FileUtils.mv '../lib/lib/libsuperlu.a', "../lib/lib/libsuperlu_#{os}_static.a"
  end
  FileUtils.cd '..'
end

desc "build superlu lib for OSX"
task :build_osx => :download do
  if File.exists?("lib/lib/libsuperlu_osx#{endname}.a") then
    puts "SuperLU already compiled"
  else
    extract_and_prepare_and_compile("osx")
  end
  Rake::Task[:install_common].invoke()
end

desc "build superlu lib for LINUX"
task :build_linux => :download do
  if File.exists?("lib/lib/libsuperlu_linux#{endname}.a") then
    puts "SuperLU already compiled"
  else
    extract_and_prepare_and_compile("linux")
  end
  Rake::Task[:install_common].invoke()
end

desc "build superlu lib for MINGW"
task :build_mingw => :download do
  if File.exists?("lib/lib/libsuperlu_mingw#{endname}.a") then
    puts "SuperLU already compiled"
  else
    extract_and_prepare_and_compile("mingw")
  end
  Rake::Task[:install_common].invoke()
end

desc "build superlu lib for WINDOWS"
task :build_win => :download do

  # check architecture
  case `where cl.exe`.chop
  when /x64\\cl\.exe/
    VS_ARCH = 'x64'
  when /amd64\\cl\.exe/
    VS_ARCH = 'x64'
  when /bin\\cl\.exe/
    VS_ARCH = 'x86'
  else
    raise RuntimeError, "Cannot determine architecture for Visual Studio".red
  end

  if File.exists?("lib/lib/libsuperlu_win_#{VS_ARCH}#{endname}.lib") then
    puts "SuperLU already compiled"
  else
    extract_and_prepare()

    FileUtils.rm_rf   "lib"
    FileUtils.mkdir_p "lib/lib"
    FileUtils.mkdir_p "lib/include"

    FileUtils.cd 'build'

    tmp = "cmake -G Ninja -DBITS:VAR=#{VS_ARCH} "

    if COMPILE_DEBUG then
      sh tmp + ' -DCMAKE_BUILD_TYPE:VAR=Debug --loglevel=STATUS ..'
      sh 'cmake --build . --clean-first --config Debug --target install '+PARALLEL
      FileUtils.mv '../lib/lib/superlu.lib', "../lib/lib/superlu_win_#{VS_ARCH}_static_debug.lib"
    else
      sh tmp + ' -DCMAKE_BUILD_TYPE:VAR=Release --loglevel=STATUS ..'
      sh 'cmake --build . --clean-first --config Release --target install '+PARALLEL
      FileUtils.mv '../lib/lib/superlu.lib', "../lib/lib/superlu_win_#{VS_ARCH}_static.lib"
    end
    FileUtils.cd '..'
  end
  Rake::Task[:install_common].invoke()
end

task :install_common do
  prefix = "../../lib3rd"
  puts "SuperLU copy files to #{prefix}"
  FileUtils.rm_rf   "#{prefix}/include/superlu"
  FileUtils.mkdir_p "#{prefix}/include/superlu"
  FileUtils.mkdir_p "#{prefix}/lib"
  Dir['lib/include/*'].each do |f|
    puts "Copy header #{f}".green
    FileUtils.cp f, prefix+'/include/superlu/'+File.basename(f)
  end
  Dir['lib/include/*'].each do |f|
    puts "Copy header #{f}".green
    FileUtils.cp f, prefix+'/include/superlu/'+File.basename(f)
  end
  Dir['lib/lib/*.*'].each do |f|
    puts "Copy static lib #{f}".green
    FileUtils.cp f, prefix+'/lib/'+File.basename(f)
  end
end

task :install_linux => :build_linux do end
task :install_osx   => :build_osx   do end
task :install_mingw => :build_mingw do end
task :install_win   => :build_win   do end

task :clean_common do
  FileUtils.rm_rf "build"
  FileUtils.rm_rf "lib"
  FileUtils.rm_rf "superlu"
end

task :clean_osx   => :clean_common do end
task :clean_linux => :clean_common do end
task :clean_mingw => :clean_common do end
task :clean_win   => :clean_common do end
