require "rake"
require_relative "../../Rakefile_common.rb"

task :default => [:install_osx]

VER='5.2.1'

desc "download superlu_#{VER}.tar.gz lib"
task :download do
  filename = "superlu_#{VER}.tar.gz"
  url_download( "http://crd-legacy.lbl.gov/~xiaoye/SuperLU/#{filename}", filename )
end

desc "build superlu lib for osx"
task :build_osx => [:download] do
  filename = "superlu_#{VER}.tar.gz"
  if File.exists?('lib/lib/libsuperlu_osx_static.a') then
    puts "SuperLU already compiled"
  else
    extract_tgz(filename)
    FileUtils.rm_rf 'superlu'
    FileUtils.mv    'SuperLU_'+VER, 'superlu'
    FileUtils.rm_rf 'build'
    FileUtils.mkdir 'build'
    FileUtils.cd    'build'
    if COMPILE_DEBUG then
      sh 'cmake -DCMAKE_BUILD_TYPE:VAR=Debug -DCMAKE_INSTALL_PREFIX:PATH=../lib --loglevel=WARNING ..'
      sh 'cmake --build . --clean-first --config Debug --target install '+PARALLEL+QUIET
      FileUtils.mv '../lib/lib/libsuperlu.a', "../lib/lib/libsuperlu_osx_static_debug.a"
    else
      sh 'cmake -DCMAKE_BUILD_TYPE:VAR=Release -DCMAKE_INSTALL_PREFIX:PATH=../lib --loglevel=WARNING ..'
      sh 'cmake --build . --clean-first --config Release --target install '+PARALLEL+QUIET
      FileUtils.mv '../lib/lib/libsuperlu.a', "../lib/lib/libsuperlu_osx_static.a"
    end
    FileUtils.cd '..'
  end
  Rake::Task[:install_common].invoke()
end

desc "build superlu lib for linux"
task :build_linux => [:download] do
  filename = "superlu_#{VER}.tar.gz"
  if File.exists?('lib/lib/libsuperlu_linux_static.a') then
    puts "SuperLU already compiled"
  else
    extract_tgz(filename)
    FileUtils.rm_rf 'superlu'
    FileUtils.mv    'SuperLU_'+VER, 'superlu'
    FileUtils.rm_rf 'build'
    FileUtils.mkdir 'build'
    FileUtils.cd    'build'
    if COMPILE_DEBUG then
      sh 'cmake -DCMAKE_BUILD_TYPE:VAR=Debug -DCMAKE_INSTALL_PREFIX:PATH=../lib --loglevel=WARNING ..'
      sh 'cmake --build . --clean-first --config Debug --target install '+PARALLEL+QUIET
      FileUtils.mv '../lib/lib/libsuperlu.a', "../lib/lib/libsuperlu_linux_static_debug.a"
    else
      sh 'cmake -DCMAKE_BUILD_TYPE:VAR=Release -DCMAKE_INSTALL_PREFIX:PATH=../lib --loglevel=WARNING ..'
      sh 'cmake --build . --clean-first --config Release --target install '+PARALLEL+QUIET
      FileUtils.mv '../lib/lib/libsuperlu.a', "../lib/lib/libsuperlu_linux_static.a"
    end
    FileUtils.cd '..'
  end
  Rake::Task[:install_common].invoke()
end

desc "build superlu lib for windows"
task :build_win, [:year, :bits] => [:download] do |t, args|
  args.with_defaults(:year => "2017", :bits => "x64" )

  if File.exists?("ibs/lib/libsuperlu_win_#{args.bits}_static.lib") and
     File.exists?("ibs/lib/libsuperlu_win_#{args.bits}_static_debug.lib") then
    puts "SuperLU already compiled"
  else
    filename = "superlu_#{VER}.tar.gz"
    extract_tgz(filename)
    FileUtils.rm_rf 'superlu'
    FileUtils.mv    'SuperLU_'+VER, 'superlu'
    dir = "vs_#{args.year}_#{args.bits}"

    FileUtils.rm_rf   dir
    FileUtils.mkdir_p dir
    FileUtils.cd      dir
    FileUtils.rm_rf   "lib"
    FileUtils.mkdir_p "lib/lib"
    FileUtils.mkdir_p "lib/include"

    tmp = win_vs(args.bits,args.year)

    if COMPILE_DEBUG then
      sh tmp + ' -DCMAKE_BUILD_TYPE:VAR=Debug --loglevel=WARNING ..'
      sh 'cmake --build . --clean-first --config Debug --target INSTALL '+PARALLEL+QUIET
      FileUtils.mv '../lib/lib/superlu.lib', "../lib/lib/superlu_win_#{args.bits}_static_debug.lib"
    else
      sh tmp + ' -DCMAKE_BUILD_TYPE:VAR=Release --loglevel=WARNING ..'
      sh 'cmake --build . --clean-first --config Release --target INSTALL '+PARALLEL+QUIET
      FileUtils.mv '../lib/lib/superlu.lib', "../lib/lib/superlu_win_#{args.bits}_static.lib"
    end
    FileUtils.cd '..'
  end
  Rake::Task[:install_common].invoke()
end

task :install_common do |t, args|
  prefix = "../../lib3rd"
  puts "SuperLU copy files to #{prefix}"
  FileUtils.rm_rf   "#{prefix}/include/superlu"
  FileUtils.mkdir_p "#{prefix}/include/superlu"
  FileUtils.mkdir_p "#{prefix}/lib"
  Dir['lib/include/*'].each do |f|
    puts "Copy header #{f}".green
    FileUtils.cp f, prefix+'/include/superlu/'+File.basename(f)
  end
  Dir['lib/include/*'].each do |f|
    puts "Copy header #{f}".green
    FileUtils.cp f, prefix+'/include/superlu/'+File.basename(f)
  end
  Dir['lib/lib/*'].each do |f|
    puts "Copy static lib #{f}".green
    FileUtils.cp f, prefix+'/lib/'+File.basename(f)
  end
  Dir['lib/lib/*'].each do |f|
    puts "Copy static lib #{f}".green
    FileUtils.cp f, prefix+'/lib/'+File.basename(f)
  end
end

desc "install locally superlu lib for linux"
task :install_linux => [:build_linux] do
end

desc "install locally superlu lib for osx"
task :install_osx => [:build_osx] do
end

desc "install locally superlu lib for windows"
task :install_win, [:year, :bits] do |t, args|
  args.with_defaults(:year => "2017", :bits => "x64" )
  Rake::Task[:build_win].invoke(args.year, args.bits)
end

desc "clean superlu for linux"
task :clean_linux do
  FileUtils.rm_rf "lib"
  FileUtils.rm_rf "superlu"
end

desc "clean superlu for osx"
task :clean_osx do
  FileUtils.rm_rf "lib"
  FileUtils.rm_rf "superlu"
end

desc "clean superlu for windows"
task :clean_win do
  FileUtils.rm_rf "lib"
  Dir['vs_*'].each do |f|
    FileUtils.rm_rf f
  end
end
