require "rake"
require "../common.rb"

desc "install locally OpenBlas for Linux (do nothing)"
task :install_linux do
end

desc "install locally OpenBlas for OSX (do nothing)"
task :install_osx do
end

desc "install locally OpenBlas for Windows"
task :install_win do
  bits = "x64"
  FileUtils.mkdir_p "../../lib3rd/lib"
  FileUtils.mkdir_p "../../lib3rd/dll"
  FileUtils.mkdir_p "../../lib3rd/include/openblas/"+bits+"/"
  Dir[bits+'/bin/*.dll'].each{ |f| FileUtils.cp(f,'../../lib3rd/dll/'+File.basename(f)) }
  Dir[bits+'/lib/*.*'].each{ |f| FileUtils.cp(f,'../../lib3rd/lib/'+File.basename(f)) }
  Dir[bits+'/include/*.h'].each{ |f| FileUtils.cp(f,'../../lib3rd/include/openblas/' + bits + '/'+File.basename(f)) }
end

task :clean_linux do
end

task :clean_osx do
end

task :clean_windows do
end
