require "rake"
require "../../Rakefile_common.rb"

desc "install locally OpenBlas for Linux (do nothing)"
task :install_linux do
end

desc "install locally OpenBlas for OSX (do nothing)"
task :install_osx do
end

desc "install locally OpenBlas for Windows"
task :install_win, [:year, :bits]  do |t, args|
  args.with_defaults(:year => "2017", :bits => "x64" )
  bits = args.bits;
  FileUtils.mkdir_p "../../lib3rd/lib"
  FileUtils.mkdir_p "../../lib3rd/dll"
  FileUtils.mkdir_p "../../lib3rd/bin/"+bits
  FileUtils.mkdir_p "../../lib3rd/include/openblas/"
  FileUtils.mkdir_p "../../lib3rd/include/openblas/"+bits+"/"
  Dir[bits+'/bin/*.dll'].each{ |f| FileUtils.cp(f,'../../lib3rd/bin/'+bits+'/'+File.basename(f)) }
  Dir[bits+'/dll/*'].each{ |f| FileUtils.cp(f,'../../lib3rd/dll/'+File.basename(f)) }
  Dir[bits+'/lib/*'].each{ |f| FileUtils.cp(f,'../../lib3rd/lib/'+File.basename(f)) }
  Dir[bits+'/include/*.h'].each{ |f| FileUtils.cp(f,'../../lib3rd/include/openblas/'+bits+'/'+File.basename(f)) }
end

desc "clean Openblas for linux"
task :clean_linux do
end

desc "clean Openblas forosx"
task :clean_osx do
end

desc "clean Openblas for windows"
task :clean_win do
end
