require "rake"
require "fileutils"

task :default => :install_osx do end

task :copy_submodules do
  FileUtils.mkdir_p "../lib3rd/"
  FileUtils.mkdir_p "../lib3rd/lib/"
  FileUtils.mkdir_p "../lib3rd/dll/"
  FileUtils.mkdir_p "../lib3rd/bin/"
  FileUtils.cp_r    "./UtilsLite/lib/include/Utils/.", "../lib3rd/include"
  FileUtils.cp_r    "./UtilsLite/lib/.", "../lib3rd"
end

desc "build 3rd parties for OSX/LINUX/MINGW"
task :build_common, [:os] do |t, args|
  args.with_defaults( :os => "osx" )
  FileUtils.cd "Utils"
  sh "rake clean_#{args.os}"
  sh "rake build_#{args.os}"
  FileUtils.cd ".."
  Rake::Task[:copy_submodules].invoke()
end

task :build_osx   do Rake::Task[:build_common].invoke("osx")   end
task :build_linux do Rake::Task[:build_common].invoke("linux") end
task :build_mingw do Rake::Task[:build_common].invoke("mingw") end
task :build_win   do Rake::Task[:build_common].invoke("win")   end

desc "clean 3rd parties for OSX/LINUX/MINGW"
task :clean_common, [:os] do |t, args|
  args.with_defaults( :os => "osx" )
  FileUtils.cd "Utils"
  sh "rake clean_#{args.os}"
  FileUtils.cd ".."
end

task :clean_osx    do Rake::Task[:clean_common].invoke("osx")   end
task :clean_linux  do Rake::Task[:clean_common].invoke("linux") end
task :clean_mingw  do Rake::Task[:clean_common].invoke("mingw") end
task :clean_win    do Rake::Task[:clean_common].invoke("win")   end
